#!/bin/sh

e=/usr/bin/server
cfg=/etc/server.conf
pidf=$(sed -e "s@pidfile[[:space:]]*=[[:space:]]*\(.*\)\|.*@\1@" -e '/^$/d' $cfg)
pid=$(cat pidf 2>/dev/null)

case "$1" in
	start)
		start-stop-daemon -SPbp $pidf -x $e
		;;
	stop)
		start-stop-daemon -KPs TERM -R SIGKILL/10 -p $pidf -x $e
		;;
	status)
		echo "unknown"
		;;
	*)
		echo "$0 start|stop|status"
		;;
esac

